### ISSUE TITLE
reduce diffs due to introducing lexicographically prior importing packages

### ISSUE THREAD

**Issue by josharian** [tailscale/depaware#4]
depaware.txt diffs can be very noisy. See e.g. the diff in https://github.com/tailscale/depaware/pull/3/commits. Many of those changes are of the form:

```diff
-        bytes                                                        from encoding/json+
+        bytes                                                        from bufio+
```

I propose that when a package is imported by >1 package, we write `<multiple packages>` instead of using `lexifirst+`. This provides less information, but will be much more stable.

Optionally, we could also add a `-all` flag (better name welcome) that spells out every single importing package like `bufio,encoding/json`, instead of `<multiple packages>`. That would be useful for someone actively trying to cut dependencies. And teams might choose to use it all the time; with a good intra-line diff, it'd generate usable diffs again.

I'm willing to implementation, but feedback on design requested first.

**Comment by bradfitz** [comment]
I want to see at least one path for debugging.

I'm fine with some occasional churn when one path is now lexicographically less.

**Comment by josharian** [comment]
For the diff in #3, 6 of the changes were new dependencies, 2 were new indirect dependencies, and 6 were lexicographic changes. That's not a great ratio.

A fancier alternative is to have depaware parse the existing depaware.txt file and attempt to preserve the existing lines if possible.

**Comment by bradfitz** [comment]
> A fancier alternative is to have depaware parse the existing depaware.txt file and attempt to preserve the existing lines if possible.

I like the sound of that.

The parsing doesn't need to be super accurate either, since it would only be picking an answer that's already valid.
